"""
html_reporter.py — 단일 HTML 파일 리포트 생성

결과를 자체 완결형 HTML로 출력한다.
외부 의존성 없이 인라인 CSS만 사용.
"""
from __future__ import annotations

import os
from datetime import datetime


def generate_html(
    results: list,
    case_name: str | None,
    host: str = "",
    samples_collected: int = 1,
    samples_total: int = 1,
) -> str:
    total = len(results)
    passed = sum(1 for r in results if r["passed"])
    status = "PASS" if passed == total else "FAIL"
    status_color = "#22c55e" if status == "PASS" else "#ef4444"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    case_display = case_name or "healthcheck"

    rows = ""
    for r in results:
        icon = "&#10004;" if r["passed"] else "&#10008;"
        color = "#22c55e" if r["passed"] else "#ef4444"
        reason = r.get("reason", "OK")
        if reason == "OK":
            reason = ""
        rows += f"""<tr>
  <td style="color:{color};font-weight:bold;text-align:center">{icon}</td>
  <td>{r['name']}</td>
  <td style="color:{color}">{"PASS" if r["passed"] else "FAIL"}</td>
  <td style="color:#6b7280;font-size:13px">{reason}</td>
</tr>
"""

    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<title>pim-check: {case_display}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:-apple-system,system-ui,sans-serif; background:#f9fafb; padding:24px; }}
  .container {{ max-width:800px; margin:0 auto; }}
  .header {{ background:#fff; border:1px solid #e5e7eb; border-radius:8px; padding:20px; margin-bottom:16px; }}
  .status {{ font-size:32px; font-weight:700; color:{status_color}; }}
  .meta {{ color:#6b7280; font-size:14px; margin-top:8px; }}
  .meta span {{ margin-right:16px; }}
  table {{ width:100%; background:#fff; border:1px solid #e5e7eb; border-radius:8px;
           border-collapse:collapse; overflow:hidden; }}
  th {{ background:#f3f4f6; text-align:left; padding:10px 12px; font-size:13px;
       color:#374151; border-bottom:1px solid #e5e7eb; }}
  td {{ padding:8px 12px; border-bottom:1px solid #f3f4f6; font-size:14px; }}
  tr:last-child td {{ border-bottom:none; }}
  .footer {{ text-align:center; color:#9ca3af; font-size:12px; margin-top:16px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="status">{status}</div>
    <div class="meta">
      <span>Case: <b>{case_display}</b></span>
      <span>Host: <b>{host}</b></span>
      <span>Checks: <b>{passed}/{total}</b></span>
      <span>Samples: <b>{samples_collected}/{samples_total}</b></span>
    </div>
    <div class="meta"><span>{timestamp}</span></div>
  </div>
  <table>
    <thead><tr><th style="width:40px"></th><th>Check</th><th style="width:60px">Result</th><th>Detail</th></tr></thead>
    <tbody>
{rows}
    </tbody>
  </table>
  <div class="footer">Generated by pim-check</div>
</div>
</body>
</html>"""


def save_html(
    results: list,
    case_name: str | None,
    host: str = "",
    samples_collected: int = 1,
    samples_total: int = 1,
    output_dir: str = "reports",
) -> str:
    """결과를 HTML 파일로 저장. 파일 경로를 반환."""
    os.makedirs(output_dir, exist_ok=True)
    html = generate_html(results, case_name, host, samples_collected, samples_total)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    case_slug = case_name or "healthcheck"
    filename = f"{case_slug}_{ts}.html"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w") as f:
        f.write(html)
    return filepath
