name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    uses: jhw7500/automation/.github/workflows/claude.yml@41131bb7843770259246e4125325a2ef4e95731f
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
